export enum ActionTypes {
  WEB3_CONNECT_WALLET = 'CONNECT_WALLET',
  WEB3_DISCONNECT_WALLET = 'DISCONNECT_WALLET',
  MAIN_APPLY_LIGHT_THEME = 'APPLY_LIGHT_THEME',
  MAIN_APPLY_DARK_THEME = 'APPLY_DARK_THEME'
}
